# Coding Project:Householder base algorithm and QR-decomposition

QR factorization
Develop a package that does a QR decomposition of a matrix using the orthogonal Householder transformation. You can find details of the algorithm here http://www.cs.cornell.edu/~bindel/class/cs6210-f09/lec18.pdf .
Make a pip package out of it including dependencies. Add CI using Travis, testing installation from pip and running on a random matrix.
Reference - http://www.maths.lth.se/na/courses/NUMA21/exercises/

In [30]:
import numpy as np

In [3]:
a = np.arange(12).reshape(3,4)

In [4]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [13]:
a = np.matrix('1 2 3; 3 4 5; 3 7 9')
a

matrix([[1, 2, 3],
        [3, 4, 5],
        [3, 7, 9]])

In [87]:
%%latex
\begin{align}
A = Q \times R \\
\end{align}

<IPython.core.display.Latex object>

In [16]:
t = np.transpose(a)
t

matrix([[1, 3, 3],
        [2, 4, 7],
        [3, 5, 9]])

In [14]:
i = np.identity(3)
i

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [15]:
inv = np.linalg.inv(a )
inv

matrix([[  2.50000000e-01,   7.50000000e-01,  -5.00000000e-01],
        [ -3.00000000e+00,  -1.48029737e-16,   1.00000000e+00],
        [  2.25000000e+00,  -2.50000000e-01,  -5.00000000e-01]])

In [17]:
a * t 

matrix([[ 14,  26,  44],
        [ 26,  50,  82],
        [ 44,  82, 139]])

Q-orthogonal matrix whose inverse is equal to the transpose (flip over diagonale)
 
R-upper triagonale matrix

both should be identified for a matrix A, composed of n vectors c1...cx , using the householder base algorithm

I-identity matrix,square matrix with one as main diagonal

In [114]:
%%latex
\begin{align}

Q^{T} \times Q = I\\
Q^{T} = Q^{-1} \\

\hat{u} = \frac{u}{|u|}\\
\end{align}

<IPython.core.display.Latex object>

In [38]:
v = np.array([1,2,3])
v = v.reshape(3,1)
v

array([[1],
       [2],
       [3]])

In [4]:
v

array([1, 2, 3])

In [5]:
v * np.transpose(v)

array([1, 4, 9])

In [7]:
np.absolute(v)

array([1, 2, 3])

In [9]:
(np.linalg.norm(v))**2

14.0

In [10]:
np.identity(1)

array([[ 1.]])

In [ ]:
r = Reflection(v)
a = array([0,2,4])
result = r * a

In [42]:
v

array([[1],
       [2],
       [3]])

The class Reflection will be initialized from the vector v and contain the following method __mul__

In [105]:
class Reflection:
    """
    Class for calculating the reflection of a vector a, initialized by a vector v
    """
    def __init__(self, v): 
        """
        Define the vector v 
        """
        self.vector = v
        gamma = ((np.linalg.norm(v))**2)/2
        vvtrans = v * np.transpose(v)
        H =  np.identity(3) - (vvtrans/gamma)
    def __mul__(self, vector):
        reflection = np.dot(H,vector)
        return(reflection) 

In [91]:
a = np.array([2,(-2),4])
a = a.reshape(3,1)
a = np.matrix(a)

In [104]:
gamma = ((np.linalg.norm(v))**2)/2
vvtrans = v * np.transpose(v)
H = np.identity(3) - (vvtrans/gamma)
np.dot(H,a)

matrix([[ 0.57142857],
        [-4.85714286],
        [-0.28571429]])

In [106]:
R = Reflection(v)
R

In [107]:
result= R * a
result

matrix([[ 0.57142857],
        [-4.85714286],
        [-0.28571429]])

In [91]:
class Point: 
    """
    Simple class for representing a point in a Cartesian coordinate system.
    """
    def __init__(self, x, y): 
        """
        Create a new Point at x, y. 
        """
        self.x = x
        self.y = y
    def translate(self, dx, dy): 
        """
        Translate the point by dx and dy in the x and y direction. 
        """
        self.x += dx
        self.y += dy
    def __str__(self):
        return("Point at [%f, %f]" % (self.x, self.y))

In [97]:
p1 = Point(0, 0) # this will invoke the __init__ method in the Point class 
print(p1) # this will invoke the __str__ method


Point at [0.000000, 0.000000]
