Task 2 use a vector of a different lenght a, such that if len(a) < len(v), raise an exception and if len(a) > len(v) add 0 at v[0], to match len(a)

In [1]:
import numpy as np

In [2]:
class Reflection:
    """
    Class for calculating the reflection of a, through the orthogonal matrix of v 
    """
    def __init__(self, v): 
        """
        Define the vector v 
        """
        self.v = v
    def __mul__(self, a):
        """
        Calculate the matrix product for the reflection through the plane with matrix H
        """
        if len(a) < len(self.v):
            raise Exception('Length of a is smaller than length of v!')
        elif len(a) > len(self.v):
            differenceav = (len(a) - len(self.v))
            add = np.zeros(differenceav)
            vresh = self.v.reshape(1,len(self.v))
            velong = np.insert(self.v,0,add).reshape(len(a),1)
            self.v = velong
        else:
            self.v = v
        gamma = ((np.linalg.norm(self.v))**2)/2
        vvtrans = self.v * np.transpose(self.v)
        H =  np.identity((len(a))) - (vvtrans/gamma)
        reflection = np.dot(H,a)
        return(reflection) 

Make the test

In [3]:
b = np.array([1,2,3])
b = b.reshape(3,1)
b

array([[1],
       [2],
       [3]])

In [4]:
c = np.array([2,(-2),5,6])
c = c.reshape(4,1)
c 

array([[ 2],
       [-2],
       [ 5],
       [ 6]])

In [7]:
g = np.array([3,4,9,(-3)])

In [10]:
r = Reflection(b)
result = r * g
result

array([ 3.        ,  2.14285714,  5.28571429, -8.57142857])