Task 3 use a matrix a such that each column will be reflected one by one

In [3]:
import numpy as np

In [2]:
class Matrix_operations:
    """
    Class for matrix operarations
    """
    def arrayn(mn):
        """
        Return number of rows
        """
        return(np.shape(mn)[0])
    def arraym(mn):
        """
        Return number of columns
        """
        return(np.shape(mn)[1])
    def array_of_columns(mn):
        """
        Return columns
        """
        arrayn = np.shape(mn)[0]
        arraym = np.shape(mn)[1]
        for b in range(arraym):
            columns =(np.hsplit(mn, mn.shape[1]))
            return(columns)

In [4]:
class Reflection:
    """
    Class for calculating the reflection of a, through the orthogonal matrix of v 
    """
    def __init__(self, v): 
        """
        Define the vector v
        """
        self.v = v  
    
    def __mul__(self, a):
        """  
        Calculate the matrix product for the 
        reflection of vector a or the vectors 
        resulting from the columns in matrix a through 
        the plane with matrix H
        """
        if len(a) < len(self.v):
            raise Exception('Length of a is smaller than length of v!')
        elif len(a) > len(self.v):
            differenceav = (len(a) - len(self.v))
            add = np.zeros(differenceav)
            vresh = self.v.reshape(1,len(self.v))
            velong = np.insert(self.v,0,add).reshape(len(a),1)
            self.v = velong
        else:
            self.v = v
        gamma = ((np.linalg.norm(self.v))**2)/2
        vvtrans = self.v * np.transpose(self.v)
        H =  np.identity((len(a))) - (vvtrans/gamma)
        reflection = np.dot(H,a)
        return(reflection) 

In [3]:
class Hauseholder:
    """
    Class for calculating the reflection of a, through the orthogonal matrix of matrix A 
    """
    def __init__(self, A): 
        """
        Define the matrix A
        """
        self.A = A
        new_matrix = np.copy(A)
    reflections = 
    def 

Make the test

In [3]:
b = np.array([1,2,3,4,7,9])
b = b.reshape(3,2)
b

array([[1, 2],
       [3, 4],
       [7, 9]])

In [10]:
h = np.array([1,2,3])
h

array([1, 2, 3])

In [6]:
c = np.matrix([2,3,4,(-2),4,7,5,9,1,6,-3,-1])
c = c.reshape(4,3)
c

matrix([[ 2,  3,  4],
        [-2,  4,  7],
        [ 5,  9,  1],
        [ 6, -3, -1]])

In [8]:
new_matrix = np.copy(c)
new_matrix

array([[ 2,  3,  4],
       [-2,  4,  7],
       [ 5,  9,  1],
       [ 6, -3, -1]])

In [11]:
r = Reflection(h)
result = r * c
result

matrix([[ 2.        ,  3.        ,  4.        ],
        [-5.71428571,  2.14285714,  6.14285714],
        [-2.42857143,  5.28571429, -0.71428571],
        [-5.14285714, -8.57142857, -3.57142857]])