Task 3 use a matrix a such that each column will be reflected one by one

In [1]:
import numpy as np

In [5]:
c = np.matrix([2,3,4,(-2),4,7,5,9,1,6,-3,-1])
c = c.reshape(4,3)
c

matrix([[ 2,  3,  4],
        [-2,  4,  7],
        [ 5,  9,  1],
        [ 6, -3, -1]])

In [20]:
class Matrix_operations:
    """
    Class for matrix operarations
    """
    def arrayn(mn):
        """
        Return number of rows
        """
        return(np.shape(mn)[0])
    def arraym(mn):
        """
        Return number of columns
        """
        return(np.shape(mn)[1])
    def array_of_columns(mn):
        """
        Return columns
        """
        arrayn = np.shape(mn)[0]
        arraym = np.shape(mn)[1]
        for b in range(arraym):
            columns =(np.hsplit(mn, mn.shape[1]))
            return(columns)

In [21]:
class Reflection:
    """
    Class for calculating the reflection of a, through the orthogonal matrix of v 
    """
    def __init__(self, v): 
        """
        Define the vector v
        """
        self.v = v  
    
    def __mul__(self, a):
        """
        Calculate the matrix product for the 
        reflection of vector a or the vectors 
        resulting from the columns in matrix a through 
        the plane of the orthogonal matrix H
        """
        if len(a) < len(self.v):
            raise Exception('Length of a is smaller than length of v!')
        elif len(a) > len(self.v):
            differenceav = (len(a) - len(self.v))
            add = np.zeros(differenceav)
            vresh = self.v.reshape(1,len(self.v))
            velong = np.insert(self.v,0,add).reshape(len(a),1)
            self.v = velong
        else:
            self.v = v
        gamma = ((np.linalg.norm(self.v))**2)/2
        vvtrans = self.v * np.transpose(self.v)
        H =  np.identity((len(a))) - (vvtrans/gamma)
        reflection = np.dot(H,a)
        return(reflection) 

Make the test

In [13]:
b = np.array([1,2,3])
b = b.reshape(3,1)
b

array([[1],
       [2],
       [3]])

In [30]:
r = Reflection(b)
result = r * c
result
Matrix_operations.array_of_columns(result)[0]

matrix([[ 2.        ],
        [-5.71428571],
        [-2.42857143],
        [-5.14285714]])

In [116]:
#vector1 = c[...,0]
#vector2 = c[...,1] 
#vector3 = c[...,2]