Task 1 for QR decomposition: reflecting a vector through a plane that is spanned by a vector with vectors v to initialize the Reflection and a the vector being reflected.

In [17]:
import numpy as np

In [13]:
class Reflection:
    """
    Class for calculating the reflection of vector a, through the orthogonal matrix of vector v 
    """
    def __init__(self,v): 
        """
        Define the vector v 
        """
        self.v = v
    def __mul__(self, a):
        """
        Calculate the matrix product for the reflection through the plane with matrix H
        """
        gamma = ((np.linalg.norm(self.v))**2)/2
        vvtrans = self.v * np.transpose(self.v)
        H =  np.identity((len(self.v))) - (vvtrans/gamma)
        reflection = np.dot( H, a)
        return(reflection) 

Make the test

In [19]:
b = np.array([1,2,3])
b = b.reshape(3,1)
b

array([[1],
       [2],
       [3]])

In [15]:
c = np.array([2,(-2),4])
c = c.reshape(3,1)
c

array([[ 2],
       [-2],
       [ 4]])

In [16]:
r = Reflection(b)
result = r * c
result

array([[ 0.57142857],
       [-4.85714286],
       [-0.28571429]])